language: python
services: mysql
install:
  - pip install tox
  - pip install MySQL-python==1.2.5
before_script:
  - mysql -e 'create database journal;'
script:
  - tox
env:
  - TOXENV=django17
  - TOXENV=coverage